#!/usr/bin/zsh

# Create the text to display the weather data

wvars_emojis=(🌡️ 💨 🌧️)
units=("°C" "kmh" "lm2")

text=""

for i in {1..3}; do
	wdata=$(awk -F ',' "{print \$${i}}" /home/carlosfol/Desktop/Git_Projects/polybar_theme/current_wdata)
	text+="${wvars_emojis[i]} ${wdata} ${units[i]}"

	if [ "${i}" -lt 3 ]; then
		text+=" | "
	fi
done

echo "${text}"


