#!/usr/bin/env python3

# Create the database and the tables within in.
import os
import sqlite3

def _fill_wvariables(cursor: sqlite3.Cursor):
    """
    Insert the values of the table WeatherVariables by executing
    the file wvariables.sql.
    """
    sql = """
    INSERT INTO WeatherVariable(name, unit) VALUES
        ('temperature', 'degC'),
        ('wind', 'kmh_deg'),
        ('precipitation', 'lm2')
    """
    cursor.execute(sql)


def create_db_schema():
    """
    Create the WeatherData database schema by executing
    the file tables.sql.
    """
    conn = sqlite3.connect("WeatherData") # Create it if it does not exist

    if not os.path.exists("tables.sql"):
        raise FileNotFoundError("The tables.sql file was not found. \
                                Check to see if this file was deleted or if its path changed.")

    cursor = conn.cursor()
    with open("tables.sql", "r") as f:
        tables = f.read()

    # Create schema and fill the table WeatherVariable
    cursor.executescript(tables)
    _fill_wvariables(cursor)

    # Commit the changes and close the connection
    conn.commit()
    conn.close()

if __name__ == "__main__":
    # Check if the database was created
    if os.path.exists("WeatherData"):
        print("The database WeatherData already exists!")
    else:
        create_db_schema()
